GET http://localhost:3000/api/datos/getDataDepartamento HTTP/1.1
Content-Type: application/json

###

GET http://localhost:3000/datos/selectCiudad HTTP/1.1
Content-Type: application/json

###

GET http://localhost:3000/rol HTTP/1.1
Content-Type: application/json